name: epi-center
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - flake8
  - ipython>=7.14.0
  - jupyterlab>=2.1.3
  - jupyterlab_code_formatter
  - networkx>=2.4
  - notebook>=6.0.3
  - numpy>=1.18.4
  - pandas>=1.0.3
  - pip>=20.1.1
  - python>=3.8.2
  - scipy>=1.4.1
  - seaborn>=0.10.1
  - statsmodels>=0.11.1
  - sphinx
  - pip:
    - grakn-client>=1.7.2
    - grpcio>=1.29.0
    - jax>=0.1.57
    - jaxlib>=0.1.37
    - nbdev>=0.2.18
    - nb_black
    - numpyro>=0.2.4
    - pyro-ppl>=1.3.1
    - recommonmark
    - sphinx_rtd_theme

